# version: '3.9'
services:
  postgres:
    image: postgres:17
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgresdb
    volumes:
      - pgdata:/var/lib/postgresql/data
  # zookeeper:
  #   image: wurstmeister/zookeeper
  #   container_name: zookeeper
  #   restart: always
  #   ports:
  #     - "2181:2181"
  # kafka:
  #   image: wurstmeister/kafka
  #   container_name: kafka
  #   restart: always
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     - KAFKA_ADVERTISED_HOST_NAME=localhost
  #     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
  #     - KAFKA_DELETE_TOPIC_ENABLE=true
  #     - KAFKA_CREATE_TOPICS=test-2:2:1,test-1:3:1,common-device-cbexternal
  nats:
    container_name: nats
    restart: always
    image: nats:latest
    ports:
      - 4222:4222 # Client Connection
      - 8222:8222 # Monitoring / HTTP
      - 6222:6222 # Cluster routes
    command: >
      -js -DV
    volumes:
      - ./nats-data:/data/jetstream
 
  redis:
    container_name: redis-stack-server
    restart: always
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
  # minio:
  #   container_name: minio
  #   image: minio/minio
  #   restart: always
  #   ports:
  #     - 9000:9000
  #     - 9001:9001
  #   environment:
  #     - MINIO_ROOT_USER=minio
  #     - MINIO_ROOT_PASSWORD=minio123
  #   volumes:
  #     - minio_storage:/data
  #   command: server /data --console-address ":9001"
    # command: server /data
  # rabbitmq:
  #   image: "rabbitmq:3.12.1-management"
  #   restart: always
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   volumes:
  #     - rabbitmq_storage:/data
  # mailpit:
  #   image: axllent/mailpit
  #   container_name: mailpit
  #   restart: always
  #   volumes:
  #     - ./data:/data
  #   ports:
  #     - 8025:8025
  #     - 1025:1025
  #   environment:
  #     MP_MAX_MESSAGES: 5000
  #     MP_DATA_FILE: /data/mailpit.db
  #     MP_SMTP_AUTH_ACCEPT_ANY: 1
  #     MP_SMTP_AUTH_ALLOW_INSECURE: 1
  mongodb:
    image: mongo:8.0
    restart: always
    ports:
      - '27017:27017'
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: mongo
    #   MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - dbdata6:/data/db
  # openldap:
  #   image: osixia/openldap
  #   container_name: openldap
  #   restart: always
  #   ports:
  #     - '389:389'
  #     - '636:636'
  #   environment:
  #     - LDAP_ORGANISATION=WIOT360
  #     - LDAP_DOMAIN=wiot360.com
  #     - LDAP_ADMIN_PASSWORD=admin
  #   volumes:
  #     - 'ldap_data:/var/lib/ldap'
  #     - 'ldap_config:/etc/ldap/slapd.d'
  # antmedia:
  #   image: antmedia/enterprise:latest
  #   container_name: antmedia
  #   ports:
  #     - "5080:5080"    # HTTP Dashboard
  #     - "5443:5443"    # HTTPS Dashboard
  #     - "1935:1935"    # RTMP
  #     - "8870:8870"    # WebRTC Signaling
  #   volumes:
  #     - ./data:/usr/local/antmedia   # Persist data
  #   restart: unless-stopped
    # entrypoint: /usr/local/antmedia/start.sh
  # otel:
  #   image: docker.io/grafana/otel-lgtm:latest
  #   restart: unless-stopped
  #   container_name: otel-lgtm
  #   ports:
  #     - "3000:3000"   # Grafana UI
  #     - "4317:4317"   # OTLP gRPC
  #     - "4318:4318"   # OTLP HTTP
  #     - "9090:9090"   # Prometheus metrics (optional)
  #   environment:
  #     # Grafana defaults
  #     - GF_SECURITY_ADMIN_USER=admin
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
 
  #     # Optional: enable logs from internals to debug
  #     - ENABLE_LOGS_ALL=true
 
  #     # Optional: you can override the default OTEL exporter endpoint for collector
  #     # - OTEL_EXPORTER_OTLP_ENDPOINT=http://your-exporter:4318
  #     # - OTEL_EXPORTER_OTLP_HEADERS=your-header=value
  #   volumes:
  #     - otel_lgtm_data:/data
  # emqx:
  #   image: emqx/emqx:6.0.0
  #   container_name: emqx
  #   restart: unless-stopped
  #   ports:
  #     - "1883:1883"     # MQTT plain
  #     - "8883:8883"     # MQTT over TLS
  #     - "8083:8083"     # WebSocket MQTT
  #     - "8084:8084"     # WebSocket MQTT over TLS
  #     - "18083:18083"   # Dashboard
  #   environment:
  #     EMQX_NAME: emqx-node
  #     EMQX_LOADED_PLUGINS: "emqx_dashboard,emqx_management"
  #     EMQX_ALLOW_ANONYMOUS: "true"  # change to false in prod
  #     EMQX_MQTT__SHARED_SUBSCRIPTION_STRATEGY: "sticky"
  #     EMQX_MQTT__MAX_INFLIGHT: "100"
  #     EMQX_MQTT__PERSISTENT_SESSION_STORE: "true"      
  #     EMQX_MQTT__SESSION_EXPIRY_INTERVAL: "7200s"
  #   volumes:
  #     - ./emqx/data:/opt/emqx/data
  #     - ./emqx/log:/opt/emqx/log
  #     # - ./emqx/etc:/opt/emqx/etc
 
volumes:
  minio_storage:
  rabbitmq_storage:
  dbdata6:
  grafana-data:
  ldap_data:
  ldap_config:
  pgdata:
  otel_lgtm_data:
 